config/routes.rb
Rails.application.routes.draw do
  resources :products do
    member do
      put :touch
    end

    collection do
      post :break_cache
    end
  end

  root 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order("id desc")
    fresh_when @products, public: false
  end

  # GET /products/1
  # GET /products/1.json
  def show
    fresh_when @product, public: false
  end

  def break_cache
    Product.update_all(:updated_at => Time.now)
    redirect_to products_path
  end

  # Just a way to show what happens when you change the updated_at on an item
  def touch
    @product = Product.find(params[:id])
    @product.touch

    redirect_to products_path
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "CacheTest" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="row">
      <main id="content" class="site-content large-12 columns" role="main">
        <%= yield %>
      </main>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<%# This cache key is based on the individual product.id and updated_at. If either of those
    have changed, the inner TR must be re-rendered. %>
<% cache product do %>
  <tr>
    <td><%= product.name %></td>

    <td><%= Time.now.strftime("%I:%M:%S:%L") %></td>
    <td><%= product.updated_at.in_time_zone("EST").strftime("%I:%M:%S:%L") %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= button_to "Touch", touch_product_path(product), method: :put, data: {disable_with: "Touching..."} %></td>
  </tr>
<% end %>

app/views/products/_product_table_row.html.erb
<%# This cache key is based on the individual product.id and updated_at. If either of those
    have changed, the inner TR must be re-rendered. %>
<% cache product do %>
  <tr>
    <td><%= product.name %></td>

    <td><%= Time.now.strftime("%I:%M:%S:%L") %></td>
    <td><%= product.updated_at.in_time_zone("EST").strftime("%I:%M:%S:%L") %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= button_to "Touch", touch_product_path(product), method: :put, data: {disable_with: "Touching..."} %></td>
  </tr>
<% end %>

app/views/products/_products_table.html.erb
<%# Cache for products is based around the ids and max(updated_at) returned by Product.all.
    If none have changed, the entire set can be rendered from fragment cache. %>
<% cache @products do %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Rendered at</th>
        <th>Updated at</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <%= render 'product_table_row', product: product %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% start_time = Time.now %>
<h1>Listing products</h1>
<h2 id="renderTime"></h2>

<%= button_to "Break products cache", break_cache_products_path, method: :post, class: "button alert", data: {disable_with: "Breaking..."} %>
<%= link_to 'New Product', new_product_path, class: "button secondary" %>

<%= render 'products_table' %>

<br>
<% end_time = Time.now %>

<script>
document.getElementById("renderTime").innerHTML = "Total render time: <%= end_time - start_time %>"
</script>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>